### ISSUE TITLE
pager_c.cs compiles with error under NET 2.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ans-ashkan/csharp-sqlite#97]
```
pager_c.cs(6550,33): error CS0172: 
Type of conditional expression cannot be determined because 'byte' and 'int'
implicitly convert to one another

```

Original issue reported on code.google.com by `noah.hart@gmail.com` on 7 Mar 2011 at 4:30
